// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KnownMonikersExplorer
{
    internal sealed partial class Vsix
    {
        public const string Id = "c38f3512-4653-4d97-a4c5-860a425209f6";
        public const string Name = "KnownMonikers Explorer 2022";
        public const string Description = @"A tool window for Visual Studio extension authors to explore the KnownMonikers image collection";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, knownmonikers, image";
    }
}
