// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KnownMonikersExplorer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidKnownMonikersPackageString = "4256ca61-2162-4ca2-8d10-4c6a2794521c";
        public static Guid guidKnownMonikersPackage = new Guid(guidKnownMonikersPackageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowToolWindowId = 0x0100;
        public const int FindMoniker = 0x0101;
    }
}